;;; devil-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from devil.el

(autoload 'devil-mode "devil" "\
Local minor mode to support Devil key sequences.

This is a minor mode.  If called interactively, toggle the `Devil
mode' mode.  If the prefix argument is positive, enable the mode,
and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `devil-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-devil-mode 'globalized-minor-mode t)
(defvar global-devil-mode nil "\
Non-nil if Global Devil mode is enabled.
See the `global-devil-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-devil-mode'.")
(custom-autoload 'global-devil-mode "devil" nil)
(autoload 'global-devil-mode "devil" "\
Toggle Devil mode in all buffers.
With prefix ARG, enable Global Devil mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Devil mode is enabled in all buffers where `devil--on' would do it.

See `devil-mode' for more information on Devil mode.

(fn &optional ARG)" t)
(register-definition-prefixes "devil" '("devil"))

;;; End of scraped data

(provide 'devil-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; devil-autoloads.el ends here
