;;; js-comint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from js-comint.el

(autoload 'js-do-use-nvm "js-comint" "\
Enable nvm.")
(autoload 'js-comint-select-node-version "js-comint" "\
Use a given VERSION of node from nvm.

(fn &optional VERSION)" t)
(autoload 'js-comint-add-module-path "js-comint" "\
Add a directory to `js-comint-module-paths'." t)
(autoload 'js-comint-delete-module-path "js-comint" "\
Delete a directory from `js-comint-module-paths'." t)
(autoload 'js-comint-save-setup "js-comint" "\
Save current setup to \".dir-locals.el\"." t)
(autoload 'js-comint-reset-repl "js-comint" "\
Kill existing REPL process if possible.
Create a new Javascript REPL process.
The environment variable `NODE_PATH' is setup by `js-comint-module-paths'
before the process starts." t)
(autoload 'js-comint-clear "js-comint" "\
Clear the Javascript REPL." t)
(autoload 'js-comint-start-or-switch-to-repl "js-comint" "\
Start a new repl or switch to existing repl." t)
(autoload 'js-comint-repl "js-comint" "\
Start a Javascript process by running CMD.
The environment variable \"NODE_PATH\" is setup by `js-comint-module-paths'.

(fn CMD)" t)
(autoload 'js-comint-send-region "js-comint" "\
Send the current region to the inferior Javascript process.
If no region selected, you could manually input javascript expression." t)
(defalias 'js-send-region 'js-comint-send-region)
(autoload 'js-comint-send-last-sexp "js-comint" "\
Send the previous sexp to the inferior Javascript process." t)
(defalias 'js-send-last-sexp 'js-comint-send-last-sexp)
(autoload 'js-comint-send-buffer "js-comint" "\
Send the buffer to the inferior Javascript process." t)
(defalias 'js-send-buffer 'js-comint-send-buffer)
(autoload 'js-comint-load-file "js-comint" "\
Load FILE into the javascript interpreter.

(fn FILE)" t)
(defalias 'js-load-file 'js-comint-load-file)
(autoload 'js-comint-mode "js-comint" "\


(fn)" t)
(register-definition-prefixes "js-comint" '("js-" "run-js" "switch-to-js"))


;;; Generated autoloads from test-js-comint.el

(register-definition-prefixes "test-js-comint" '("js-comint-test-"))

;;; End of scraped data

(provide 'js-comint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; js-comint-autoloads.el ends here
