;;; ormolu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ormolu.el

 (autoload 'ormolu-format-buffer "ormolu" nil t)
 (autoload 'ormolu-format-region "ormolu" nil t)
 (autoload 'ormolu-format-on-save-mode "ormolu" nil t)
(register-definition-prefixes "ormolu" '("ormolu"))

;;; End of scraped data

(provide 'ormolu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ormolu-autoloads.el ends here
