;;; dune-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dune.el

(autoload 'dune-mode "dune" "\
Major mode to edit dune files.
For customization purposes, use `dune-mode-hook'.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\(?:\\`\\|/\\)dune\\(?:\\.inc\\|\\-project\\|\\-workspace\\)?\\'" . dune-mode))
(autoload 'dune-promote "dune" "\
Promote the correction for the current file." t)
(autoload 'dune-runtest-and-promote "dune" "\
Run tests in the current directory and promote the current buffer." t)
(register-definition-prefixes "dune" '("dune-"))


;;; Generated autoloads from dune-flymake.el

(register-definition-prefixes "dune-flymake" '("dune-flymake-"))


;;; Generated autoloads from dune-watch.el

(register-definition-prefixes "dune-watch" '("dune-watch-" "start-dune-watch"))

;;; End of scraped data

(provide 'dune-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dune-autoloads.el ends here
