;;; sly-repl-ansi-color-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sly-repl-ansi-color.el

(register-definition-prefixes "sly-repl-ansi-color" '("sly-repl-ansi-"))

;;; End of scraped data

(provide 'sly-repl-ansi-color-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sly-repl-ansi-color-autoloads.el ends here
